vpr200_tester: test TOUCHnn inputs
Signed-off-by: Marc Reilly <marc@cpdesign.com.au>

diff --git a/arch/arm/boards/vpr200_tester/env/bin/init b/arch/arm/boards/vpr200_tester/env/bin/init
--- a/arch/arm/boards/vpr200_tester/env/bin/init
+++ b/arch/arm/boards/vpr200_tester/env/bin/init
@@ -29,6 +29,19 @@ if [ x$? != x0 ]; then
 	sleep 5
 fi
 
+echo "Testing TOUCHnn inputs"
+tsinputs_test
+if [ x$? != x0 ]; then
+	# solid red
+	i2c_write -a 0x08 -r 0x35 0x00 0x09 0xfd
+	i2c_write -a 0x08 -r 0x36 0x00 0x00 0x00
+	echo "Error testing TOUCHnn inputs"
+	HASERROR="1"
+
+	sleep 5
+fi
+
+
 # leds off
 i2c_write -a 0x08 -r 0x35 0x00 0x00 0x00 
 i2c_write -a 0x08 -r 0x36 0x00 0x00 0x00 
