vpr200: tester: add check for checking devices
This checks that basic device files were created for mc13xxx, eeprom
nor and nand.

Signed-off-by: Marc Reilly <marc@cpdesign.com.au>

diff --git a/arch/arm/boards/vpr200_tester/env/bin/init b/arch/arm/boards/vpr200_tester/env/bin/init
--- a/arch/arm/boards/vpr200_tester/env/bin/init
+++ b/arch/arm/boards/vpr200_tester/env/bin/init
@@ -59,6 +59,12 @@ if [ x$? != x0 ]; then
 	HASERROR="1"
 fi
 
+/env/bin/test_devices
+if [ x$? != x0 ]; then
+	echo "Error testing DEVICES"
+	HASERROR="1"
+fi
+
 echo Tests finished
 echo $HASERROR
 if [ x$HASERROR = x0 ]; then
